# Generated by Django 4.1.2 on 2022-11-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
