# Generated by Django 4.1.2 on 2022-11-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_construction_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='description',
            field=models.TextField(blank=True, max_length=295, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
