# Generated by Django 4.1.2 on 2022-11-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username_alter_profile_name'),
        ('constructions', '0004_alter_construction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
