# Generated by Django 4.1.2 on 2022-11-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0008_alter_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='tags',
        ),
        migrations.AddField(
            model_name='construction',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constructions.tag'),
        ),
    ]
