# Generated by Django 4.1.2 on 2022-11-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0009_remove_construction_tags_construction_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='tags',
        ),
        migrations.AlterField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructions.construction'),
        ),
        migrations.AddField(
            model_name='construction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='constructions.tag'),
        ),
    ]
