# Generated by Django 4.1.2 on 2022-11-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0011_alter_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.AddField(
            model_name='tag',
            name='constructions',
            field=models.ManyToManyField(blank=True, to='constructions.construction'),
        ),
    ]
