# Generated by Django 4.1.2 on 2022-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0015_alter_tag_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
