# Generated by Django 4.1.2 on 2022-11-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0019_tag_owner_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='constructions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructions.construction'),
        ),
    ]
