# Generated by Django 4.1.2 on 2022-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0021_remove_tag_constructions_remove_construction_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='construction',
            name='tags',
        ),
        migrations.AddField(
            model_name='construction',
            name='tags',
            field=models.ManyToManyField(blank=True, to='constructions.tag'),
        ),
    ]
