# Generated by Django 4.1.2 on 2022-11-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0028_others'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concrete',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='construction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='earth',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='others',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='reinforcement',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created']},
        ),
    ]
