# Generated by Django 4.1.2 on 2022-11-30 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0031_alter_construction_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='concrete',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='earth',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='others',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='reinforcement',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='concrete',
            name='measure_unit',
            field=models.ManyToManyField(to='constructions.tag'),
        ),
        migrations.AddField(
            model_name='earth',
            name='measure_unit',
            field=models.ManyToManyField(to='constructions.tag'),
        ),
        migrations.AddField(
            model_name='others',
            name='measure_unit',
            field=models.ManyToManyField(to='constructions.tag'),
        ),
        migrations.AddField(
            model_name='reinforcement',
            name='measure_unit',
            field=models.ManyToManyField(to='constructions.tag'),
        ),
    ]
