# Generated by Django 4.1.2 on 2022-11-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0032_measureunit_remove_concrete_measure_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasureUnit',
        ),
        migrations.RemoveField(
            model_name='concrete',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='earth',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='others',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='reinforcement',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='concrete',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='earth',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='others',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reinforcement',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
