# Generated by Django 4.1.2 on 2022-11-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0034_measureunit_alter_concrete_measure_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasureUnit',
        ),
    ]
