# Generated by Django 4.1.2 on 2022-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0036_measureunit_alter_concrete_name_alter_earth_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earth',
            name='measure_units',
            field=models.ManyToManyField(blank=True, to='constructions.measureunit'),
        ),
    ]
