# Generated by Django 4.1.2 on 2022-11-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0039_earth_measure_units_remove_earth_measure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earth',
            name='measure_units',
        ),
        migrations.RemoveField(
            model_name='earth',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='earth',
            name='measure_unit',
            field=models.ManyToManyField(blank=True, to='constructions.measureunit'),
        ),
    ]
