# Generated by Django 4.1.2 on 2022-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0042_remove_earth_measure_units_remove_earth_measure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earth',
            name='measure_unit',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='earth',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
