# Generated by Django 4.1.2 on 2022-12-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0046_earth_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earth',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='earth',
            name='measure_unit',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='MeasureUnit',
        ),
        migrations.AddField(
            model_name='earth',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
