# Generated by Django 4.1.2 on 2022-12-01 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0047_remove_earth_unit_remove_earth_measure_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='earth',
            name='measure_unit_dropdown',
            field=models.ManyToManyField(blank=True, to='constructions.measureunit'),
        ),
    ]
