# Generated by Django 4.1.2 on 2022-12-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0051_remove_earth_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earth',
            name='measure_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
