# Generated by Django 4.1.2 on 2022-12-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0055_others_measure_unit_dropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concrete',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='earth',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='others',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='reinforcement',
            name='measure_unit',
        ),
        migrations.AddField(
            model_name='earth',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
