# Generated by Django 4.1.2 on 2022-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0056_remove_concrete_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concrete',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
