# Generated by Django 4.1.2 on 2022-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0059_others_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concrete',
            name='custom_name',
            field=models.CharField(default='Position Custom Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='name',
            field=models.CharField(default='Position Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='concrete',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='earth',
            name='custom_name',
            field=models.CharField(default='Position Custom Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='earth',
            name='name',
            field=models.CharField(default='Position Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='earth',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='others',
            name='custom_name',
            field=models.CharField(default='Position Custom Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='others',
            name='name',
            field=models.CharField(default='Position Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='others',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='reinforcement',
            name='custom_name',
            field=models.CharField(default='Position Custom Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='reinforcement',
            name='name',
            field=models.CharField(default='Position Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='reinforcement',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
